-- ============================================
-- 指标管理系统 - 数据库初始化脚本
-- Database: Oracle
-- ============================================

-- 创建序列
CREATE SEQUENCE SEQ_INDICATOR_CATEGORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_INDICATOR_DEF START WITH 1 INCREMENT BY 1;

-- 指标分类表
CREATE TABLE INDICATOR_CATEGORY (
    CATEGORY_ID   NUMBER(10) PRIMARY KEY,
    CATEGORY_CODE VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORY_NAME VARCHAR2(200) NOT NULL,
    PARENT_ID     NUMBER(10) DEFAULT 0,
    SORT_ORDER    NUMBER(5) DEFAULT 0,
    STATUS        CHAR(1) DEFAULT '1',
    CREATE_TIME   DATE DEFAULT SYSDATE,
    UPDATE_TIME   DATE
);

-- 指标定义表
CREATE TABLE INDICATOR_DEF (
    INDICATOR_ID   NUMBER(10) PRIMARY KEY,
    INDICATOR_CODE VARCHAR2(100) NOT NULL UNIQUE,
    INDICATOR_NAME VARCHAR2(200) NOT NULL,
    CATEGORY_ID    NUMBER(10),
    QUERY_SQL      CLOB,
    PARAM_DEF      VARCHAR2(500),
    DESCRIPTION    VARCHAR2(500),
    DATA_TYPE      VARCHAR2(20) DEFAULT 'LIST',
    UNIT           VARCHAR2(50),
    STATUS         CHAR(1) DEFAULT '1',
    VERSION        NUMBER(5) DEFAULT 1,
    CREATE_TIME    DATE DEFAULT SYSDATE,
    UPDATE_TIME    DATE,
    CREATE_USER    VARCHAR2(50),
    UPDATE_USER    VARCHAR2(50)
);

-- 外键约束
ALTER TABLE INDICATOR_DEF ADD CONSTRAINT FK_INDICATOR_CATEGORY
    FOREIGN KEY (CATEGORY_ID) REFERENCES INDICATOR_CATEGORY(CATEGORY_ID);

-- 注释
COMMENT ON TABLE INDICATOR_CATEGORY IS '指标分类表';
COMMENT ON COLUMN INDICATOR_CATEGORY.CATEGORY_ID IS '分类ID';
COMMENT ON COLUMN INDICATOR_CATEGORY.CATEGORY_CODE IS '分类编码';
COMMENT ON COLUMN INDICATOR_CATEGORY.CATEGORY_NAME IS '分类名称';
COMMENT ON COLUMN INDICATOR_CATEGORY.PARENT_ID IS '父分类ID';
COMMENT ON COLUMN INDICATOR_CATEGORY.SORT_ORDER IS '排序号';
COMMENT ON COLUMN INDICATOR_CATEGORY.STATUS IS '状态：1-启用 0-禁用';
COMMENT ON COLUMN INDICATOR_CATEGORY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN INDICATOR_CATEGORY.UPDATE_TIME IS '更新时间';

COMMENT ON TABLE INDICATOR_DEF IS '指标定义表';
COMMENT ON COLUMN INDICATOR_DEF.INDICATOR_ID IS '指标ID';
COMMENT ON COLUMN INDICATOR_DEF.INDICATOR_CODE IS '指标编码（英文标识）';
COMMENT ON COLUMN INDICATOR_DEF.INDICATOR_NAME IS '指标名称';
COMMENT ON COLUMN INDICATOR_DEF.CATEGORY_ID IS '所属分类ID';
COMMENT ON COLUMN INDICATOR_DEF.QUERY_SQL IS '查询SQL模板（支持参数占位符 #{param}）';
COMMENT ON COLUMN INDICATOR_DEF.PARAM_DEF IS '参数定义（JSON格式）';
COMMENT ON COLUMN INDICATOR_DEF.DESCRIPTION IS '指标说明';
COMMENT ON COLUMN INDICATOR_DEF.DATA_TYPE IS '返回值类型：SINGLE/LIST';
COMMENT ON COLUMN INDICATOR_DEF.UNIT IS '单位';
COMMENT ON COLUMN INDICATOR_DEF.STATUS IS '状态：1-启用 0-禁用';
COMMENT ON COLUMN INDICATOR_DEF.VERSION IS '版本号';
COMMENT ON COLUMN INDICATOR_DEF.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN INDICATOR_DEF.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN INDICATOR_DEF.CREATE_USER IS '创建人';
COMMENT ON COLUMN INDICATOR_DEF.UPDATE_USER IS '更新人';
